### ISSUE TITLE
YAML file lists the observers to be initialized

### ISSUE THREAD

**Issue by hsd-dev** [hsd-dev/rosgraph_monitor-backup#21]
This can also include input params like link to the ROS models in case of `ROSGraphObserver`.

**Comment by hsd-dev** [comment]
http://wiki.ros.org/roslaunch/XML/rosparam#Examples   

in launch file:  
```
<rosparam command="load" file="$(find rosparam)/example.yaml" />
```
to access in python code:
```
ros::NodeHandle nh;
double number_to_get;
nh.getParam("/custom_prefix/number_float", number_to_get);
```
Another option is to set param as path to YAML file and use `YAML` module in python to load and read file:
https://github.com/udacity/CarND-Capstone/blob/master/ros/src/camera_info_publisher/yaml_to_camera_info_publisher.py

**Comment by hsd-dev** [comment]
Example file:
```
observers:
  - name: QualityObserver
      - topic: /speed
        type: std_msgs/Float64
      - topic: /accel
        type: std_msgs/Int32
      - hz: 100
  - name: ROSGraphIbserver
      - model: resources/talker_listener.rossystem
      - hz: 10
```
